task: "controlnet"
sub_task: "image_to_image"
experiment_name: ""


# Model Configs
personalized_model: "/path/to/model"
model_type: "sd1.5"
controlnet_model: "/path/to/model"
res_adapter_model: "models/res_adapter/sd1.5"
res_adapter_alpha: 1.0


# Inference Configs
width: null
height: null
scale_ratio: 1.5  # scale the original image

num_inference_steps: 25
guidance_scale: 7.5
num_images_per_prompt: 8

source_images: [
  "assets/controlnet/bird.png",
]

prompts: [
  "bird",
]

n_prompt: "lowres, bad anatomy, worst quality, low quality"


# Other Configs
enable_xformers: true
enable_compare: true
draw_text: false
seed: 42
device: 0
split_images: true