task: "t2i"
experiment_name: "dreamshaper-resadapter-re"

# Model Configs
personalized_model: "/path/to/model"
model_type: "sd1.5"
res_adapter_model: "models/res_adapter/sd1.5"
res_adapter_alpha: 1.0

# Inference Configs
width: 256
height: 1024
num_inference_steps: 25
guidance_scale: 7.5
num_images_per_prompt: 8

prompts: [
  "(masterpiece), (extremely intricate), (realistic), portrait of a girl, the most beautiful in the world, (medieval armor), metal reflections, upper body, outdoors, intense sunlight, far away castle, professional photograph of a stunning woman detailed, sharp focus, dramatic, award winning, cinematic lighting, octane render unreal engine, volumetrics dtx, (film grain, blurry background, blurry foreground, bokeh, depth of field, sunset, motion blur), chainmail",
  "portrait, action pose, slow motion, (old male human wizard:1.2) old male human wizard wearing yellow and black robes (majestic evoker cloth armor:1.2), (wrinkles, steampunk), (archmage robes, runic patterns:1.2), (insanely detailed, bloom:1.5), (analog:1.2), (high sharpness), (detailed pupils:1.1), (painting:1.1), (digital painting:1), detailed face and eyes, Masterpiece, best quality, (highly detailed photo:1.1), 8k, photorealistic, very long straight white and grey hair, grey streaks, ecstatic, (60-year old Austrian male:1.1), sharp, (older body:1.1), stocky, realistic, real shadow 3d, (highest quality), (concept art, 4k), (wizard labratory in backgound:1.2), by Michelangelo and Alessandro Casagrande and Greg Rutkowski and Sally Mann and jeremy mann and sandra chevrier and maciej kuciara, inspired by (arnold schwarzenegger:1.001) and (Dolph Lundgren:1.001) and (Albert Einstien:1.001)",
]

n_prompt: "ugly, deformed, noisy, blurry, nsfw, low contrast, text, BadDream, 3d, cgi, render, fake, anime, open mouth, big forehead, long neck"

# Other Configs
enable_xformers: true
enable_compare: true
draw_text: true
seed: 42
device: 0
split_images: false